chore: gh workflow updated

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,69 +1,75 @@
 name: Deploy to WordPress.org Repository
+
 on:
   release:
     types: [released]
+
 jobs:
   deploy_to_wp_repository:
     name: Deploy to WP.org
     runs-on: ubuntu-latest
     env:
       PLUGIN_SLUG: bit-smtp
-      DRY_RUN: false
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          version: 9
-
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        shell: bash
-        run: |
-          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
-
-      - uses: actions/cache@v3
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-
-      - name: Install frontend dependencies
-        run: pnpm install
 
       - name: Setup PHP
         id: setup-php
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '7.x'
+          php-version: '8.x'
           tools: composer:v2, wp-cli
 
-      - name: Get Composer cache directory
-        id: composer-cache
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
+        with:
+          run_install: false
+
+      - name: Get pnpm store directory
+        id: pnpm-cache
         shell: bash
         run: |
-          echo "COMPOSER_CACHE_PATH=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+          echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
 
-      - uses: actions/cache@v3
-        name: Setup composer cache
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - uses: actions/cache@v4
+        name: Setup package cache
         with:
-          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_PATH }}
-          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
+          path: |
+            ${{ steps.pnpm-cache.outputs.dir }}
+            ${{ steps.composer-cache.outputs.dir }}
+          key: ${{ runner.os }}-cached-package-${{ hashFiles('**/pnpm-lock.yaml', '**/composer.lock') }}
           restore-keys: |
-            ${{ runner.os }}-composer-cache-
+            ${{ runner.os }}-cached-package-
 
-      - name: Install php dependencies
-        run: composer i --no-dev --optimize-autoloader
+      - name: Check for SVN
+        id: check_svn
+        run: |
+          if ! command -v svn &> /dev/null; then
+            echo "SVN not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y subversion
+          else
+            echo "SVN is already installed."
+          fi
+
+      - name: Determine if this is a release or push
+        id: set-test-action
+        run: |
+          if [[ "${{ github.event_name }}" == "release" ]]; then
+            echo "TEST_ACTION=false" >> $GITHUB_ENV
+          else
+            echo "TEST_ACTION=true" >> $GITHUB_ENV
+          fi
 
       - name: Build
         id: build-plugin
@@ -71,19 +77,30 @@ jobs:
           pnpm build
           pnpm i18n:parse-js
           pnpm i18n:php
+          bash .github/copy-assets
+
+          if [ -d "${{ github.workspace }}/build/${{ env.PLUGIN_SLUG }}" ]; then
+            echo "free_exists=true" >> "${GITHUB_OUTPUT}"
+          else
+            echo "free_exists=false" >> "${GITHUB_OUTPUT}"
+          fi
 
       - name: WordPress Plugin Deploy
+        if: steps.build-plugin.outputs.free_exists == 'true'
         id: deploy
         uses: 10up/action-wordpress-plugin-deploy@stable
         with:
           generate-zip: true
-          dry-run: ${{ env.DRY_RUN }}
+          dry-run: ${{ env.TEST_ACTION }}
         env:
           SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
           SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
+          BUILD_DIR: '${{ github.workspace }}/build/${{ env.PLUGIN_SLUG }}'
           SLUG: ${{ env.PLUGIN_SLUG }}
+          ASSETS_DIR: '${{ github.workspace }}/svn-assets'
 
       - name: Upload release asset
+        if: steps.build-plugin.outputs.free_exists == 'true'
         uses: softprops/action-gh-release@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
